default_platform(:ios)

platform :ios do
  desc "Build and distribute iOS app via Firebase"
  lane :firebase_distribution do
    build_app(
      scheme: "Runner",
      export_method: "ad-hoc"
    )

    firebase_app_distribution(
      app: "1:673362975186:ios:959d0842d25b3e4418900b",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      ipa_path: "./build/ios/Runner.ipa",
      testers: "mostafahamed3003@gmail.com",
      release_notes: "First Fastlane Firebase Distribution for iOS!"
    )
  end
end
