name: adv_project
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.4+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.0.0
  firebase_core: ^3.11.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.4
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.17
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  get_it: ^8.0.3
  intl: ^0.20.2
  json_annotation: ^4.8.1
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.0.0
  shared_preferences: ^2.5.2
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  retrofit_generator: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
    - assets/images/splash.png
